# Use the specific Nginx image (version 1.24.0) as the base image
FROM nginx:alpine


# Copy your custom project configuration to the Nginx sites-available directory
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf


CMD ["nginx" ,"-g" , "daemon off;"]
